global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wildfly_microprofile'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['wildfly:9990']

  - job_name: 'wildfly_jmx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['wildfly:9090']